# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMZ_SVNLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField()),
                ('author', models.CharField(max_length=20)),
                ('log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XMZ_URTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('revision', models.CharField(max_length=10)),
                ('task', models.IntegerField()),
            ],
        ),
    ]
