# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmz_urtracker',
            name='task',
            field=models.TextField(),
        ),
    ]
