# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMZ', '0002_auto_20161128_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmz_svnlog',
            name='svnDate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
