# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXSY', '0002_xxsy_svnlog_svndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='xxsy_urtracker',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
